// Local-only browser smoke test. Uses an isolated browser and QA API data directory.
const {chromium}=require('playwright')
const path=require('node:path')
;(async()=>{
  const browser=await chromium.launch({headless:true,executablePath:chromium.executablePath()})
  const page=await browser.newPage({viewport:{width:360,height:740}})
  const errors=[];page.on('pageerror',e=>errors.push(e.message))
  await page.goto('http://127.0.0.1:5173')
  await page.getByRole('button',{name:'家长版',exact:true}).click()
  for(const name of ['养生','问一问','跟着练']){
    await page.getByRole('button',{name,exact:true}).click()
    const geometry=await page.evaluate(()=>({horizontal:document.documentElement.scrollWidth-innerWidth,main:document.querySelector('main').scrollHeight-document.querySelector('main').clientHeight}))
    console.log(name,geometry)
    if(geometry.horizontal>1||geometry.main>1)throw new Error(`${name} overflow`)
  }
  await page.getByRole('button',{name:/八段锦.*双手托天/}).click()
  await page.screenshot({path:'.tmp-qa-motion.png'})
  await page.getByRole('button',{name:'养生提醒设置'}).click()
  await page.getByRole('checkbox',{name:'到点提醒我'}).check()
  await page.getByRole('button',{name:'下一步：选时间'}).click()
  await page.getByLabel('什么时候提醒').waitFor()
  await page.getByRole('button',{name:'关闭',exact:true}).click()
  await page.goto('http://127.0.0.1:5173/#admin')
  await page.getByLabel('管理凭证').fill('local-qa-only')
  await page.getByRole('button',{name:'进入管理台'}).click()
  await page.getByRole('button',{name:'冥想音频',exact:true}).click()
  await page.getByRole('button',{name:'添加音频',exact:true}).click()
  await page.getByLabel('或上传文件').last().setInputFiles(path.resolve('.tmp-qa-tone.wav'))
  await page.getByLabel('音频链接').last().waitFor()
  await page.waitForFunction(()=>[...document.querySelectorAll('audio')].some(a=>a.getAttribute('src')?.includes('/api/audio/')))
  await page.getByRole('button',{name:'发布配置',exact:true}).click()
  await page.getByText('配置已发布到网站与 App。',{exact:true}).waitFor()
  await page.getByRole('button',{name:'关闭后台'}).click()
  await page.getByRole('button',{name:'养生',exact:true}).click()
  await page.getByRole('button',{name:/放松呼吸/}).click()
  await page.getByRole('button',{name:'开始三分钟'}).click()
  await page.waitForFunction(()=>{const a=document.querySelector('audio');return a&&!a.paused&&a.currentTime>0})
  await page.getByRole('button',{name:'暂停一下'}).click()
  if(!await page.locator('audio').evaluate(a=>a.paused))throw new Error('Audio not paused')
  if(await page.getByRole('button',{name:'换一段',exact:true}).isEnabled()){
    const old=await page.locator('audio').getAttribute('src')
    await page.getByRole('button',{name:'换一段',exact:true}).click()
    if(old===await page.locator('audio').getAttribute('src'))throw new Error('Audio immediately repeated')
  }
  await page.getByRole('button',{name:'关闭',exact:true}).click()
  if(await page.locator('audio').count())throw new Error('Audio retained after exit')
  await page.getByRole('button',{name:'问一问',exact:true}).click()
  await page.screenshot({path:'.tmp-qa-knowledge.png'})
  if(errors.length)throw new Error(errors.join('\n'))
  console.log('PASS: compact layouts, parent reminder steps, upload/publish/play/pause/exit')
  await browser.close()
})().catch(e=>{console.error(e);process.exit(1)})
