const {chromium}=require('playwright')
;(async()=>{
 const browser=await chromium.launch({headless:true,executablePath:chromium.executablePath()})
 try{
 const context=await browser.newContext({viewport:{width:393,height:852}}),page=await context.newPage(),errors=[]
 page.on('pageerror',e=>errors.push(e.message))
 await page.addInitScript(()=>{window.petAudio=[];const Original=window.Audio;window.Audio=function(...args){const a=new Original(...args);a.addEventListener('playing',()=>window.petAudio.push(a.src));return a}})
 await page.route('**/api/generate',route=>route.fulfill({json:{lines:['准备一杯温水。'],sources:[],basis:'general',generated:true}}))
 await page.goto(process.env.PET_QA_URL||'http://127.0.0.1:4174')
 await page.getByText('养令——练对，也练开心。',{exact:true}).waitFor()
 await page.getByRole('dialog',{name:'欢迎来到养令'}).waitFor({state:'detached'})
 const pet=page.getByRole('button',{name:'小芽，点击互动，拖动可移动'})
 await pet.click()
 await page.waitForFunction(()=>window.petAudio.some(x=>x.endsWith('pet_hello_01.mp3')))
 await page.screenshot({path:'.tmp-pet-home.png'})
 const b=await pet.boundingBox(),count=await page.evaluate(()=>window.petAudio.length)
 await page.mouse.move(b.x+35,b.y+45);await page.mouse.down();await page.mouse.move(50,400,{steps:12});await page.mouse.up()
 const moved=await pet.boundingBox();if(Math.abs(moved.x-b.x)<50)throw new Error('Pet did not drag')
 if(await page.evaluate(()=>window.petAudio.length)!==count)throw new Error('Drag triggered click')
 await page.getByRole('button',{name:'收起小芽'}).click()
 const small=page.getByRole('button',{name:'展开小芽'}),sb=await small.boundingBox()
 await page.mouse.move(sb.x+20,sb.y+20);await page.mouse.down();await page.mouse.move(sb.x+80,sb.y+30,{steps:8});await page.mouse.up()
 await small.waitFor({state:'visible'})
 await page.getByRole('button',{name:'展开小芽'}).click()
 await page.getByRole('button',{name:/一杯 喝/}).click()
 await pet.waitFor({state:'hidden'})
 await page.getByRole('button',{name:'我喝好了',exact:true}).click()
 await page.waitForFunction(()=>window.petAudio.some(x=>x.endsWith('done_cup_01.mp3')))
 await page.getByText('今天已完成 1/3 项',{exact:true}).waitFor()
 await page.evaluate(async()=>{await navigator.serviceWorker.ready})
 await page.waitForFunction(async()=>{const keys=await caches.keys();for(const key of keys){const c=await caches.open(key);const files=await c.keys();if(files.filter(x=>x.url.includes('/audio/companion/')).length===13)return true}return false},{},{timeout:60000})
 await page.evaluate(async()=>{const files=await(await fetch('companion-assets.json')).json();for(const file of files.filter(x=>x.endsWith('.mp3'))){const buffer=await(await fetch(file)).arrayBuffer();const ac=new AudioContext();const decoded=await ac.decodeAudioData(buffer);if(decoded.duration<.2||decoded.duration>15)throw new Error(file+' duration');await ac.close()}})
 await context.setOffline(true)
 await page.waitForTimeout(5100)
 await pet.click()
 await page.waitForFunction(()=>window.petAudio.filter(x=>x.endsWith('pet_hello_01.mp3')).length===2)
 await context.setOffline(false)
 await page.setViewportSize({width:360,height:740})
 await page.getByRole('button',{name:'家长版',exact:true}).click()
 await page.screenshot({path:'.tmp-pet-parent.png'})
 if(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth))throw new Error('Horizontal overflow')
 if(errors.length)throw new Error(errors.join('\n'))
 console.log('PASS pet drag/click, no drag speech, hide/expand, real completion audio, 13 clips decoded/cached, offline greeting, parent layout')
 }finally{await browser.close()}
})().catch(e=>{console.error(e);process.exit(1)})
