const {chromium}=require('playwright')
;(async()=>{
  const browser=await chromium.launch({headless:true,executablePath:chromium.executablePath()})
  const page=await browser.newPage({viewport:{width:1440,height:900}})
  const errors=[];page.on('pageerror',e=>errors.push(e.message))
  const response=await page.goto('https://yangling.entermodetwo.com',{waitUntil:'networkidle'})
  if(response.status()!==200)throw new Error('Website unavailable')
  await page.getByRole('heading',{name:'今天感觉怎么样？'}).waitFor()
  console.log('desktop',await page.locator('[data-testid="mobile-app"]').evaluate(el=>({width:el.clientWidth,height:el.clientHeight})))
  await page.setViewportSize({width:393,height:852})
  await page.getByRole('button',{name:'问答知识库',exact:true}).click()
  await page.getByRole('textbox',{name:'输入你想问的问题'}).fill('八段锦与睡眠的研究')
  await page.getByRole('button',{name:'发送问题'}).click()
  await page.getByRole('button',{name:/知识依据 3/}).waitFor()
  await page.getByRole('button',{name:/知识依据 3/}).click()
  await page.getByRole('dialog',{name:'知识依据'}).waitFor()
  const sources=await page.locator('.ylm-source-detail').count()
  if(sources!==3)throw new Error('Research sources missing')
  if(errors.length)throw new Error(errors.join('\n'))
  console.log('PASS: production desktop/mobile, research question, three source excerpts')
  await browser.close()
})().catch(e=>{console.error(e);process.exit(1)})
